ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE sessions ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE sessions ALTER COLUMN expires_at TYPE TIMESTAMP;
ALTER TABLE threads ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE messages ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE reports ALTER COLUMN created_at TYPE TIMESTAMP;