ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE sessions ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE sessions ALTER COLUMN expires_at TYPE TIMESTAMPTZ;
ALTER TABLE threads ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE messages ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE reports ALTER COLUMN created_at TYPE TIMESTAMPTZ;
