ALTER TABLE threads 
ALTER COLUMN lat TYPE NUMERIC(8,6),
ALTER COLUMN lat SET DEFAULT 0,
ALTER COLUMN lat SET NOT NULL;

ALTER TABLE threads 
ALTER COLUMN long TYPE NUMERIC(9,6),
ALTER COLUMN long SET DEFAULT 0,
ALTER COLUMN long SET NOT NULL;