ALTER TABLE threads 
ALTER COLUMN lat TYPE DOUBLE PRECISION,
ALTER COLUMN lat SET DEFAULT 0,
ALTER COLUMN lat SET NOT NULL;

ALTER TABLE threads 
ALTER COLUMN long TYPE DOUBLE PRECISION
ALTER COLUMN long SET DEFAULT 0,
ALTER COLUMN long SET NOT NULL;