CREATE TABLE sessions (
    user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '1 MONTH'),
    token TEXT NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
);