CREATE TABLE threads (
    id SERIAL PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    long DOUBLE PRECISION NOT NULL DEFAULT 0,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
)